# TODO add a docker file to build a running MySQl/Postgres database
# You need to make sure from the persistency of the data
# The database can be a simple Schema e.g. users table only with id as a primary key as well as name, age, email and password fields
# The table will have only 5 columns/fields
# Look for how to set the db password inside the Dockerfile :)
